### ISSUE TITLE
evaluation of model complexity from a model files perspective

### ISSUE THREAD

**Issue by slawler** [TexasDIS/metadata#1]
Maybe there should be more specificity with respect to model description. For example, if we assume that models will be in more specific categories that `Water Model`. A few examples that come to mind are

 - Hydraulic Model (e.g. HEC-RAS)
 - Hydrologic Model (e.g. HEC-HMS)
 - Coastal Model (e.g. Delft3D)
 
There may even need to be refinement beyond this however, to differentiate hydraulic models for pipe flow vs surface flow. Or Hydraulic models coupled with hydrodynamic models, or doing combined riverine-coastal (Delft suite, Mike Suite, RAS suite etc.). 

https://github.com/TexasDIS/metadata/blob/87c36a9a072eeb0e3b2fe64f1b8c1c2314173868/examples_and_templates/metadata_twdb_example_data_artifact_level_2021_10_06.yaml#L29

Also thinking about the broader issues, beyond classification of models using the `data_artifact_title` line, there may need to be clear differentiation between model input and output files.
https://github.com/TexasDIS/metadata/blob/87c36a9a072eeb0e3b2fe64f1b8c1c2314173868/examples_and_templates/metadata_twdb_example_data_artifact_level_2021_10_06.yaml#L2

For most of the models there are input and file output types that are identifiable via extensions. Often there will be  model input files available, but not model outputs.

**Comment by ajdabrowski** [comment]
Thanks! We'll take a look at those repos. We've taken a first pass at generic model metadata fields with an update to the documentation published here. I'll be reaching out to you soon to schedule a discussion, and hope the update here can become a talking point. For now, I'll close this issue and we can follow-up with new ones as we see that further things need to be accounted for.
