### ISSUE TITLE
Roles for TexasDIS

### ISSUE THREAD

**Issue by dhardestylewis** [TexasDIS/metadata#5]
@brentporter

Can TDIS members be added to the TexasDIS GitHub organization and assigned roles/permissions?

**Comment by lamfletcher** [comment]
Specifically, we'd like to know if Greg, Paul, and/or I can "take over" ownership of the metadata repository and update files as needed.

**Comment by wmobley** [comment]
@lamfletcher  I gave you admin access and Paul and Greg write access.
